Initial full cycle working

diff --git a/docker-images/ship/bin/init b/docker-images/ship/bin/init
--- a/docker-images/ship/bin/init
+++ b/docker-images/ship/bin/init
@@ -16,12 +16,12 @@ function get_checksum() {
 }
 
 function sync_slug() {
-  echo "Downloading $app-latest from $SLUG_SERVER"
-  wget -qO $slug_file $slug_url
+  echo "Downloading $app-latest from $slug_server_url"
+  wget -qO $slug_file $slug_url || (rm $slug_file && echo 'wget failed' && exit 1) 
 
   echo $(get_checksum) > $checksum_file
   expected_checksum=$(cat $checksum_file)
-  slug_checksum=$(/usr/bin/shasum -a 512 $slug_file | /usr/bin/awk -F '\ ' '{print $1}' -)
+  slug_checksum=$(/usr/bin/sha512sum $slug_file | /usr/bin/awk -F ' ' '{print $1}' -)
 
   if [[ "$expected_checksum" == "$slug_checksum" ]]; then
     echo "Checksum verification passed"
@@ -31,21 +31,21 @@ function sync_slug() {
   
   echo "Extracting slug"
   mkdir -p $app_dir
-  tar -xzf $slug_file -C $app_dir 
+  tar -xzf $slug_file -C $app_dir
+  sleep 1
 }
 
 # Ensure the environment is defined
 ensure_defined "SLUG_SERVER"
 ensure_defined "APP_NAME"
 
-app="$APP_NAME"
+app=`echo $APP_NAME | sed 's/"//g'`
 
 app_dir="/app"
-cache="/srv/data"
 
 procfile="$app_dir/Procfile"
 
-slug_server_url="http://$SLUG_SERVER"
+slug_server_url=`echo "http://$SLUG_SERVER" | sed 's/"//g'`
 
 slug_file="$cache/slug.tgz"
 slug_url="$slug_server_url/$app-latest.tgz"
@@ -55,23 +55,7 @@ checksum_url="$slug_server_url/$app-latest.sha512"
 
 # TODO handle slug server unavailability
 
-echo "Checking for previous slug"
-
-if [[ -e "$slug_file" ]]; then
-  echo "Matching existing slug with server's latest version"
-  local_checksum=cat $checksum_file
-  remote_checksum=get_checksum
-  if [[ "$local_checksum" -eq "$remote_checksum" ]]; then
-    echo "Checksums match, using existing slug"
-  else
-    echo "Checksums differ, cleaning existing slug"
-    rm -fr $app_dir $slug_file $checksum_file
-    sync_slug
-  fi
-else
-  echo "No slug found, pulling from the server"
-  sync_slug
-fi
+sync_slug
 
 types=$(ruby -e "require 'yaml';puts YAML.load_file('$procfile').keys().join(', ')")
 echo "Procfile declares types -> $types"
@@ -80,8 +64,10 @@ cd $app_dir
 
 echo "Sourcing the app's env"
 for file in profile.d/*; do
+  echo "Sourcing $file"
   source $file
 done
 
-echo "Starting Procfile with Forego"
-shoreman start
+sleep 1
+echo "Starting Procfile with Shoreman"
+PORT=5000 shoreman
